server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menu-service/**

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /api/gateway-service/actuator
      exposure:
        include: prometheus, metrics, health, refresh, busrefresh, httptrace
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}